/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.proto;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AddressBookProtos.Person person = AddressBookProtos.Person.newBuilder()
                .setName("Tom Jones")
                .setEmail("abc@gs.com")
                .addPhones(
                        AddressBookProtos.Person.PhoneNumber.newBuilder()
                                .setNumber("07394050666").setType(AddressBookProtos.Person.PhoneType.WORK)
                                .build()
                ).addPhones(
                        AddressBookProtos.Person.PhoneNumber.newBuilder()
                                .setNumber("02084954956").setType(AddressBookProtos.Person.PhoneType.HOME)
                                .build()
                ).build();

        System.out.println(person);
        System.out.println(new App().getGreeting());
    }
}
